<div id="ot-lp-add-app">
    <h3>Add New Application</h3>
    <form action="/add" method="post">
        <fieldset>
            <label for="title">Title</label>
            <input id="title" name="app-title" type="text" />
            <label for="url">URL</label>
            <input id="url" name="app-url" type="text" />
            <label for="graphic">Graphic (URL)</label>
            <input id="graphic" name="app-graphic" type="text" />
            <label for="adaptive"><input id="adaptive" name="app-adaptive" type="checkbox" /> Adaptive?</label>
        </fieldset>
        <input class="btn btn-primary" type="submit" value="Submit" />
        <input class="btn btn-link" type="reset" value="Clear" />
    </form>
</div>