<div id="ot-lp-controlbar">
    <a class="btn btn-primary" href="<?php echo $this->baseUrl(); ?>/applications/add" title="Add Application">Add Application</a>
</div>
<div id="ot-lp-apps">
    <div class="ot-lp-app active">
        <img class="ot-lp-app-graphic" src="<?php echo $this->baseUrl(); ?>/images/default-graphic.png" />
        <h5 class="ot-lp-app-title"><a href="" title="App Title">App Title</a></h5>
        <h4 class="ot-lp-app-status">Active</h4>
    </div>
    <div class="ot-lp-app active">
        <img class="ot-lp-app-graphic" src="<?php echo $this->baseUrl(); ?>/images/default-graphic.png" />
        <h5 class="ot-lp-app-title"><a href="" title="App Title">App Title</a></h5>
        <h4 class="ot-lp-app-status">Active</h4>
    </div>
    <div class="ot-lp-app active">
        <img class="ot-lp-app-graphic" src="<?php echo $this->baseUrl(); ?>/images/default-graphic.png" />
        <h5 class="ot-lp-app-title"><a href="" title="App Title">App Title</a></h5>
        <h4 class="ot-lp-app-status">Active</h4>
    </div>
    <div class="ot-lp-app active">
        <img class="ot-lp-app-graphic" src="<?php echo $this->baseUrl(); ?>/images/default-graphic.png" />
        <h5 class="ot-lp-app-title"><a href="" title="App Title">App Title</a></h5>
        <h4 class="ot-lp-app-status">Active</h4>
    </div>
    <div class="ot-lp-app active">
        <img class="ot-lp-app-graphic" src="<?php echo $this->baseUrl(); ?>/images/default-graphic.png" />
        <h5 class="ot-lp-app-title"><a href="" title="App Title">App Title</a></h5>
        <h4 class="ot-lp-app-status">Active</h4>
    </div>
    <div class="ot-lp-app active">
        <img class="ot-lp-app-graphic" src="<?php echo $this->baseUrl(); ?>/images/default-graphic.png" />
        <h5 class="ot-lp-app-title"><a href="" title="App Title">App Title</a></h5>
        <h4 class="ot-lp-app-status">Active</h4>
    </div>
</div>